### ISSUE TITLE
Node 20 upgrade

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-gradebook#385]
### Description

See the parent ticket for the general description and motivation, https://github.com/openedx/public-engineering/issues/267.  Make sure to follow its recommendations for each step of the process.

```[tasklist]
- [ ] https://github.com/openedx/frontend-app-gradebook/pull/404
- [ ] https://github.com/openedx/frontend-app-gradebook/pull/406
- [ ] https://github.com/openedx/frontend-app-gradebook/pull/408
```

**Comment by farhaanbukhsh** [comment]
can I take this up @arbrandes ?

**Comment by arbrandes** [comment]
@farhaanbukhsh, sorry for the delay in replying. :)  Once we get going with this, yes, I'll take all the help I can get!  But we should probably wait a little more so we can tackle most MFEs at around the same time.

**Comment by Anas12091101** [comment]
Hi @farhaanbukhsh, I noticed you expressed interest in taking up this issue. Are you still planning to work on it? If not, @arbrandes I’m happy to take it on behalf of my team at MIT.

**Comment by farhaanbukhsh** [comment]
Hey @Anas12091101 I am still waiting for @arbrandes green flag :)

Although you can take this up if you want.

**Comment by brian-smith-tcril** [comment]
@Anas12091101 @farhaanbukhsh thank you both for offering to take this on!

@Anas12091101: I know you are taking on https://github.com/openedx/frontend-app-communications/issues/199 - I'm not sure if you'd rather take on both or have @farhaanbukhsh take this one. Let me know what works best for you!

**Comment by Anas12091101** [comment]
Thanks for the heads-up, @brian-smith-tcril! @farhaanbukhsh, feel free to take this one. I'll dive into the communications MFE in the meantime
